### PR TITLE
Rewrite using React + Next.js

### PR DESCRIPTION
**Pull request by lukecarr**
Came across Lapce on r/Rust and, wow! Really eager to see where this project goes.

I'm admittedly a new(ish)comer to Rust, and don't feel comfortable enough with the language to make some contributions to the codebase in that aspect, but I have done a fair bit of full-stack webdev, so thought I'd have a crack at the website.

I've rewritten the site in this PR to use Next.js (fully typed). The releases (version string and download URLs for assets) are automatically fetched from GitHub's REST API using a serverless function.

Where possible, I've tried to use Next.js's image optimizations, so hopefully, page load times are still fairly snappy.

I've also tried to maintain as high a [Lighthouse](https://developers.google.com/web/tools/lighthouse) as possible:

image

Would love to hear your thoughts; I've got it running on Netlify at the following URL: https://lapche-nextjs.netlify.app/

### CODE REVIEW

**Comment by lukecarr** [comment]
Reworked some stuff in the hero to use next/image, now achieving near-perfect scores:

image

Specifically, in regards to performance, before (current site):

image

After (this PR): 

image

I'm also hosting on Netlify which I've found to be slower than Vercel in personal testing.

**Comment by dzhou121** [comment]
This looks amazing. 

I'm not familiar with netxjs, but can I still host it on github pages?

**Comment by lukecarr** [comment]
> This looks amazing. 
> 
> 
> 
> I'm not familiar with netxjs, but can I still host it on github pages?

In theory, Next.js supports [Static HTML Exporting](https://nextjs.org/docs/advanced-features/static-html-export), but it doesn't support serverless functions (which this PR uses to fetch release data from GitHub).

I've always found Netlify really easy to use for deploying Next.js; they also have a [system](https://www.netlify.com/legal/open-source-policy) for giving OSS projects a free paid plan, which Lapce would definitely qualify for.

Happy to discuss more on Discord (@LukeTWT) if that's easier.

**Comment by dzhou121** [comment]
Can you resolve the conflict and I'll merge

**Pull request closed without merging**
